dist: trusty
sudo: false

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libxml-xpath-perl
      - libboost-all-dev
      - omniorb
      - omniidl
      - omniorb-nameserver
      - libomniorb4-dev
      - pkg-config
      - g++-5
      - clang-3.8

env:
  global:
    - EXTRA_CMAKE_ARGS="-DENABLE_TESTS=ON -DENABLE_CORBA=ON -DCORBA_IMPLEMENTATION=OMNIORB"
    - BOOST_TEST_LOG_LEVEL=message
    - CFLAGS="-Wall -Wextra -Wno-unused-parameter"

matrix:
  include:
    - env: COMPILER=gcc CXXFLAGS="-std=c++03 -Wall -Wextra -Wno-unused-parameter"
    - env: COMPILER=gcc CXXFLAGS="-std=c++11 -Wall -Wextra -Wno-unused-parameter"
    - env: COMPILER=gcc-5 CXXFLAGS="-std=c++03 -Wall -Wextra -Wno-unused-parameter"
    - env: COMPILER=gcc-5 CXXFLAGS="-std=c++11 -Wall -Wextra -Wno-unused-parameter"
    - env: COMPILER=clang CXXFLAGS="-std=c++03 -Wall -Wextra -Wno-unused-parameter"
    - env: COMPILER=clang CXXFLAGS="-std=c++11 -Wall -Wextra -Wno-unused-parameter"
    - env: COMPILER=clang-3.8 CXXFLAGS="-std=c++03 -Wall -Wextra -Wno-unused-parameter"
    - env: COMPILER=clang-3.8 CXXFLAGS="-std=c++11 -Wall -Wextra -Wno-unused-parameter"

branches:
  only:
  - master
  - /^toolchain-.*$/

before_install:
  # Set C/C++ compiler
  - |
    if [[ "${COMPILER}" != "" ]]; then
      export CC=${COMPILER}
      if [[ "${COMPILER}" == "gcc"* ]]; then
        export CXX=${COMPILER/gcc/g++}
      elif [[ "${COMPILER}" == "clang"* ]]; then
        export CXX=${COMPILER/clang/clang++}
      fi
      ${CC} --version
      ${CXX} --version
    fi

  # Create build directory
  - mkdir -p build && cd build

script:
  # Build and install RTT
  - cmake .. -DCMAKE_INSTALL_PREFIX=$(pwd)/install ${EXTRA_CMAKE_ARGS}
  - make -j2 install

  # Run tests
  - make -j1 check
